---
title: "exercises_week10"
author: "Lindsey Greenhill"
date: "4/7/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(contrasts = rep("contr.treatment",2))
save.image()
library(MASS)
library(stargazer)
library(tidyverse)
```

# Question 2

```{r include = FALSE}

# reading in data

nes <- foreign::read.dta("http://www.stat.columbia.edu/~gelman/arm/examples/nes/nes5200_processed_voters_realideo.dta") %>% 
  filter(year == 2000) %>%
  select(partyid3,age, gender, race, educ1, income, ideo7)

# recoding and cleaning data. Taken from a pset a while back

nes_clean <- nes %>%
  drop_na() %>%
  filter(partyid3 != "9. apolitical (1966 only: and dk)") %>%
  mutate(
    gender = as.numeric(str_sub(gender, 1, 1)) - 1,
    educ1 = as.double(str_sub(educ1, 1, 1)),
    partyid3 = as_factor(str_sub(partyid3, 1, 1)),
    income = as.double(str_sub(income, 1, 1)),
    ideo7 = as.double(str_sub(ideo7, 1, 1)),
    race = as_factor(str_sub(race, 1, 1))
  ) %>%
  #mutate(partyid3 = if_else(partyid3 == 3, "R",
   #                         if_else(partyid3 == 2, "I", "D"))) %>%
  mutate(race = case_when(race == 1 ~ "white",
                          race == 2 ~ "black",
                          race == 3 ~ "asian",
                          race == 4 ~ "native_american",
                          race == 5 ~ "hispanic"))

nes_clean_simple <- nes_clean %>%
 select(-race, -gender)
```


## Part a

```{r}

# creating multinomial logit

mod_1 <- polr(factor(partyid3) ~ age + educ1 + income + ideo7 + race,
              data = nes_clean)

# creating probit model

mod_2 <- polr(factor(partyid3) ~ age + educ1 + income + ideo7 + race,
              data = nes_clean,
              method = "probit")

# summary of both models

summary(mod_1)
summary(mod_2)

# graphs of both models. Make these like the ones in 6.4 of the textbook

invlogit <- function(Xb) {
  1/(1+exp(-Xb))
}

expected <- function (x, c1.5, c2.5, sigma){ 
  p1.5 <- invlogit ((x-c1.5)/sigma) 
  p2.5 <- invlogit ((x-c2.5)/sigma)  
  return ((1*(1-p1.5) + 2*(p1.5-p2.5) + 3*p2.5))
} 

# multi model

{
plot (nes_clean$ideo7, nes_clean$partyid3, xlim=c(0,12), ylim=c(1,3), 
      xlab="Ideology", ylab="Party")
lines (rep (mod_1$zeta[1]/mod_1$coefficients[4], 2), c(1,2)) 
lines (rep (mod_1$zeta[2]/mod_1$coefficients[4], 2), c(2,3))  
curve (expected (
  x, mod_1$zeta[1]/mod_1$coefficients[4],
  mod_1$zeta[2]/mod_1$coefficients[4],
  1/mod_1$coefficients[4]),
  add=TRUE) 
}

```

